#!/usr/bin/env bash

# create a vpc
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "10.0.0.0/16" \
--region us-east-1 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Env,Value=Dev}]' \
--query "Vpc.VpcId" \
--output text)


aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames "{\"Value\":true}"


echo "VPC created with success"

# Create a Internet Gateway
IG_ID=$(aws ec2 create-internet-gateway \
--output text \
--query InternetGateway.InternetGatewayId)

echo "Internet Gateway created with success"

# Atach the internet gateway on the VPC
aws ec2 attach-internet-gateway --internet-gateway-id "${IG_ID}" --vpc-id "${VPC_ID}"

echo "Internet Gateway attached with success"

# Creating a subnet
SUBNET_ID=$(aws ec2 create-subnet \
--cidr-block 10.0.0.0/24 \
--vpc-id "${VPC_ID}" \
--query Subnet.SubnetId \
--output text)


aws ec2 modify-subnet-attribute \
--subnet-id "${SUBNET_ID}" \
--map-public-ip-on-launch
echo "subnet Created with success"

# Update the route table
ROUTE_TABLE_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc_id,Values=${VPC_ID}" "Name=association.main,Values=true" \
--query 'RouteTables[0].RouteTableId' \
--output text)

aws ec2 associate-route-table \
--subnet-id "${SUBNET_ID}" \
--route-table-id "${ROUTE_TABLE_ID}" \
--output text

# Create Route
aws ec2 create-route \
--route-table-id "${ROUTE_TABLE_ID}" \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id "${IG_ID}"