#!/usr/bin/env bash

if [ -z $1 ]; then
echo "Please, chouse the stack you want to delete"
exit 1
fi

STACK_NAME=$1

aws cloudformation deploy \
--template-file ../IAC/cloudformation/template.yaml \
--region "us-east-1" \
--stack-name "${STACK_NAME}"
